version: '3'

services:
  pulsaeraclient:
    depends_on:
      - pulsaeradb
    build:
      context: ./client
      dockerfile: Dockerfile
    image: pulsaeraclient
    container_name: pulsaera-client
    restart: always
    ports:
      - 5173:5173
    environment:
      VITE_SERVER_URL: 'http://localhost:3000/api'
  pulsaeradb:
    depends_on:
      - db
    build: 
      context: ./server
      dockerfile: Dockerfile
    image: pulsaera
    container_name: pulsaera-app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_URI_PROD: ${DB_URI_PROD}
      DB_URI: ${DB_URI}
      NODE_ENV: 'development'
  db:
    image: mongo:5
    container_name: pulsaeradb-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: pulsaeradb
    volumes:
      - ./mongo:/data/db