version: '3'

services:
  pulsaera:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: pulsaera
    container_name: pulsaera-app
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_URI_PROD: ${DB_URI_PROD}
      NODE_ENV: 'production'
  db:
    image: mongo:5
    container_name: pulsaeradb-db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: pulsaeradb
    volumes:
      - ./mongo:/data/db